name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Latest Npm
        run: npm install -g npm@next-7

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        if: startsWith(matrix.node-version, '12.')

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Check nothing was forgotten before commit
        if: startsWith(matrix.node-version, '12.')
        run: npx repository-check-dirty
